### ISSUE TITLE
Relatório

### ISSUE THREAD

**Issue by gissandrogama** [gissandrogama/registration_system#19]
# Exportar dados e resultado de pesquisas para Excel e PDF (Orçar)
   * Gerar arquivos em pdf e excel a partir das pesquisas realizadas.

obs.: Equipe tem que decidir o valor dessa funcionalidade.

**Comment by franknfjr** [comment]
Seguimos para o arquivo CSV. No qual ficará a cargo do cliente tabular as informações como achar necessário.
